name: pdf_learner_v2
description: PDF 문서 학습 및 관리 도구
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  
  # 환경설정
  flutter_dotenv: ^5.1.0
  
  # 상태관리
  provider: ^6.0.5
  
  # PDF 관련
  syncfusion_flutter_pdfviewer: ^29.1.33
  path_provider: ^2.0.15
  file_picker: ^9.2.2
  pdf_render: ^1.4.0
  flutter_pdfview: ^1.3.0
  
  # 유틸리티
  intl: ^0.19.0
  shared_preferences: ^2.2.0
  cross_file: ^0.3.3+6
  desktop_drop: ^0.5.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.4
  http: ^1.2.0
  js: ^0.7.2

  # 추가 필요한 패키지들
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  google_sign_in: ^6.1.4
  get_it: ^8.0.3
  injectable: ^2.1.2
  uuid: ^4.5.1
  syncfusion_flutter_pdf: ^29.1.33
  sign_in_with_apple: ^6.1.4
  share_plus: ^10.1.4
  permission_handler: ^11.2.0
  package_info_plus: ^8.3.0
  webview_flutter: ^4.5.0
  flutter_secure_storage: ^10.0.0-beta.4
  image_picker: ^1.0.7
  mime: ^2.0.0
  universal_html: ^2.2.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7
  path: ^1.9.1
  firebase_analytics: ^11.4.4
  firebase_crashlytics: ^4.3.4
  firebase_performance: ^0.10.1+4
  firebase_remote_config: ^5.4.2
  flutter_local_notifications: ^19.0.0
  google_mobile_ads: ^5.3.1
  in_app_purchase: ^3.1.13
  device_info_plus: ^11.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/icons/ 